version: 2
jobs:
  build:
    docker:
      - image: quay.io/fenicsproject/stable:latest
    steps:
      - checkout
      - run:
          name: Run Unit tests
          command: |
            pytest-3 Tests/unit/
      - run:
          name: Run Integration tests
          command: |
            pytest-3 Tests/integration/
      - run:
          name: Run System tests
          command: |
            pytest-3 Tests/system/